name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: quarchive
          POSTGRES_PASSWORD: quarchive
          POSTGRES_DB: quarchive_test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      memcached:
        image: memcached
        ports:
        - 11211:11211
        options: --entrypoint memcached
      rabbitmq:
        image: rabbitmq:3.7
        env:
          RABBITMQ_DEFAULT_VHOST: test
        ports:
          - 5672:5672


    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install required ubuntu packages
      run: sudo apt-get update && sudo apt-get install -y libsystemd-dev pngcrush
    - name: Use cache of pip downloads
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('src/server/setup.py') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install tox
      run: pip install tox
    - name: Use cache of tox
      uses: actions/cache@v1
      with:
        path: src/server/.tox
        key: ${{ runner.os }}-tox
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Use cache of npm
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('src/extension/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Make
      run: make
      env:
        QM_SQL_URL_TEST: postgresql+psycopg2://quarchive:quarchive@localhost/quarchive_test
    - name: Store server artefact
      uses: actions/upload-artifact@v2
      with:
        path: dist/*.whl
    - name: Store chrome artefact
      uses: actions/upload-artifact@v2
      with:
        path: dist/*chrome.zip
    - name: Store firefox artefact
      uses: actions/upload-artifact@v2
      with:
        path: dist/*firefox.zip
